### ISSUE TITLE
DELETE {{SERVER}}/customerAddresses/{{customer_address}}

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#11]
Returning:
{
  "error": true,
  "reason": "Internal Server Error"
}

**Comment by hhanesand** [comment]
works for me...

**Comment by hhanesand** [comment]
make sure you're calling it with the right id?

**Comment by hhanesand** [comment]
you can't delete an address if you don't own it

**Comment by jasgan** [comment]
For some reason it works now LOL
