### ISSUE TITLE
PATCH product's tag via {{SERVER}}/products/{id} not working?

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#12]
I think PATCHing changes to a product's tag isn't working. e.g. PATCHing {"tags" : [2]} doesn't change the product's tag to 2.

**Comment by hhanesand** [comment]
oh my mistake I didnt tell you patching like that is not supported

I'll set up something for this

**Comment by hhanesand** [comment]
how do you want this to work? Would you like one end point to remove or add a specific tag? or just somewhere where you can do what you tried to do above?

**Comment by jasgan** [comment]
Yeah could you add modifying tags to be a part of PATCHing a product?

**Comment by hhanesand** [comment]
yeah but do you want :

1. `PATCH /products` with a `"tags" : []` array that completely replaces all the tags
2. `DELETE` and `POST` to `/products/{product_id}/tags/{tag_id}` (like how pictures works)

**Comment by jasgan** [comment]
I think Number 2 would work better

**Comment by hhanesand** [comment]
This is now live! It's on postman in the create and delete folders.

**Comment by jasgan** [comment]
If it's not too difficult, could you also enable "1. PATCH /products with a "tags" : [] array that completely replaces all the tags"?

**Comment by hhanesand** [comment]
Yeah sure! Are you still going to be using the first implementation?

**Comment by jasgan** [comment]
Sweet and no I don't think so
