### ISSUE TITLE
Get Order based on Order_ID

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#13]
Can you create an endpoint for getting 1 order based on the order id?
Like this:
{{SERVER}}/orders/{**ORDER_ID**}?type=maker&fulfilled=false

**Comment by hhanesand** [comment]
done! this includes all the info for the maker, ping me if you need this for the customer side too

**Comment by jasgan** [comment]
Ya could you do this for the customer side too?

**Comment by hhanesand** [comment]
done
