### ISSUE TITLE
Return corresponding subscription based on order_id

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#14]
For "subscriptions", instead of returning an array[...], can you just return the corresponding subscription with the 'order_id' matching the order's ['id']?

"id": 37,
    "card": "card_1AMCF4DIUJ4QuxdkE82BgczT",
    "customer": {
      "id": 3,
      "stripe_id": "cus_AhWTEZOUA4Xata",
      "sub_id": "GYr1nvC3uPRp8lfs9rtyoN5e8xl2",
      "name": "Jasper Gan",
      "email": "jasper.gan@berkeley.edu"
    },
    "subscriptions": [
      {
        "fulfilled": false,
        "id": 32,
        "subcriptionIdentifier": "sub_AoiC3egZwaCUAt",
        "maker_id": 13,
        "variants": {
          "17": "Medium"
        },
        "order_id": 37,
        "offer_id": null,
        "oneTime": false,
        "product_id": 25,
        "subscribed": true
      }
    ],

**Comment by hhanesand** [comment]
That has to be an array, since you added the ability for multiple subscriptions in an order.
