### ISSUE TITLE
IMPORTANT: Order Timestamps

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#15]
Can you include a timestamp of when the order was placed (for subscriptions and one-time) as well as for each upcoming renewal date (for subscriptions only **not** one-time)?

**Comment by hhanesand** [comment]
I can give you a timestamp of when the order was placed, and the period length of the subscription. Does that work for you?

**Comment by jasgan** [comment]
yeah that works!

**Comment by hhanesand** [comment]
did this
