### ISSUE TITLE
Return customer name for Reviews

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#24]
For GET "{{SERVER}}/products/{BOX_ID}?expand=tags,maker,pictures,variants,reviews", under "reviews," could you return the customer name instead of the customer_id?

**Comment by hhanesand** [comment]
There is a new "author" field that is returned now

**Comment by hhanesand** [comment]
it is automatically set to the user's name when the review is created
the old ones won't have anything set here
