### ISSUE TITLE
Track Coupon Clicks/Claims

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#3]
Track which user (based on cookie) clicks on which coupons. Each time they click a coupon, it would be added to their dashboard. So I think I would send a /POST request with the product ID, coupon ID + user's cookie and the API would create a connection between those 3 elements. Then when I call /GET it would return all the coupon ID's, product ID's, associated with that user.

**Comment by hhanesand** [comment]
in postman "Get Coupon Clicks"

**Comment by hhanesand** [comment]
you don't have to submit the product id, just the offer_id of the coupon they clicked on
