### ISSUE TITLE
For {{SERVER}}/makers?expand=stripe,pictures could you return the maker's logo URL?

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#5]

**Comment by hhanesand** [comment]
yeah!

**Comment by hhanesand** [comment]
I've implemented this now. What do you want to display on `?expand=stripe`?

**Comment by jasgan** [comment]
Could you display last 4 digits, expiry?

**Comment by hhanesand** [comment]
Yeah, you just want the user's cards from stripe?

**Comment by hhanesand** [comment]
I can do that

**Comment by jasgan** [comment]
wait scratch that lol the maker doesn't have cards right only the user
