### ISSUE TITLE
Firebase User Authentication

### ISSUE THREAD

**Issue by jasgan** [instacrate/tapcrate-api#9]
I created a new Firebase user and then signed in. But when I called "{{SERVER}}/authentication?type=customer" I got an error - "reason": "Failed to verifiy claims with error JWT error: Claim verification failed for claim with name: aud."

This was the body:
{
  "token" : "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlYzQ2NWJkMTNhN2RhY2RmNTQ1ODk0OTJiMTdjZDNmNDFiNWNlNmYifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGFwY3JhdGUiLCJuYW1lIjoiSmFzcGVyIEdhbiIsImF1ZCI6InRhcGNyYXRlIiwiYXV0aF90aW1lIjoxNDk1Mjg0NTkzLCJ1c2VyX2lkIjoiR1lyMW52QzN1UFJwOGxmczlydHlvTjVlOHhsMiIsInN1YiI6IkdZcjFudkMzdVBScDhsZnM5cnR5b041ZTh4bDIiLCJpYXQiOjE0OTUyODQ1OTQsImV4cCI6MTQ5NTI4ODE5NCwiZW1haWwiOiJqYXNwZXIuZ2FuQGJlcmtlbGV5LmVkdSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYXNwZXIuZ2FuQGJlcmtlbGV5LmVkdSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.KIScEumoKmSKBuIKq_T70YLbTY2vWibs75X4h8a040L4WNi3bxhF-f4gUro_1mzimv98YMNTsMhGoBUGXBu4NEWtRsKCqvaj702bFVNtMjQ5ecsFt3C89n8BA-bxC30pY1EA16JekREzW32zfcEfUC5txuXKqmcAk7wS_zjnrHqYxL4EMcfEfxT8-2e1BIFpstLh3EYTHZnP1tCWPTkmYoDMe0bxdOMrgS9bYfZbbV4ceik2pzBaI95W41C2B1P-Ksbb2qzjO86RNPpk1TxgRd3nEg_IhViIllEiLXIku0mEUVWJn_IzGSp3xtcbDATjq8og-PQCz-hrrr4s75rsEA",
  "subject" : "GYr1nvC3uPRp8lfs9rtyoN5e8xl2",
  "providerData" : {
    "displayName" : "Jasper Gan",
    "email" : "jasper.gan@berkeley.edu"
  }
}

**Comment by hhanesand** [comment]
fixed
